name: Quality Item
description: An item worth addressing during a quality day.
title: "[Quality]: "
labels: ["quality"]
projects: ["MT-JEDI/9"]
body:
  - type: textarea
    id: info
    attributes:
      label: Describe the idea
      description: Provide any additional that may help someone accomplish this task
    validations:
      required: true
